joint_space_c = [0,0,0,0];

end_effector_c = df_matrix(0,    0,   0,  joint_space_c(1))...
             * df_matrix(20,   0,   0,  joint_space_c(2))...
             * df_matrix(20,   0,   0,  joint_space_c(3))...
             * df_matrix(5,    0,   0,  joint_space_c(3))

joint_space_d = [pi/2,0,0,0];

end_effector_d = df_matrix(0,    0,   0,  joint_space_d(1))...
             * df_matrix(20,   0,   0,  joint_space_d(2))...
             * df_matrix(20,   0,   0,  joint_space_d(3))...
             * df_matrix(5,    0,   0,  joint_space_d(3))