joint_space_c = [0,0,0,0];

end_effector_c = dh_matrix(0,    0,   0,  joint_space_c(1))...
             * dh_matrix(20,   0,   0,  joint_space_c(2))...
             * dh_matrix(20,   0,   0,  joint_space_c(3))...
             * dh_matrix(5,    0,   0,  joint_space_c(3))

joint_space_d = [pi/2,0,0,0];

end_effector_d = dh_matrix(0,    0,   0,  joint_space_d(1))...
             * dh_matrix(20,   0,   0,  joint_space_d(2))...
             * dh_matrix(20,   0,   0,  joint_space_d(3))...
             * dh_matrix(5,    0,   0,  joint_space_d(3))